/*TODOS*/
export const TODOS_FILTER = 'TODOS_FILTER';
export const CHANGE_TODOS_FOCUS = 'CHANGE_TODOS_FOCUS';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const TODOS_TREE_CLEAR = 'TODOS_TREE_CLEAR';
export const UPDATE_TODOS_ALL = 'UPDATE_TODOS_ALL';
export const UPDATE_TODOS_FETCH = 'UPDATE_TODOS_FETCH';
export const CHANGE_LOADING = 'CHANGE_LOADING';

/*INPUT*/
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const CHANGE_MODAL_NAME_VALUE = 'CHANGE_MODAL_NAME_VALUE';
export const CHANGE_MODAL_CHECK_VALUE = 'CHANGE_MODAL_CHECK_VALUE';

/*MODAL*/
export const CHANGE_MODAL_VISIBLE = 'CHANGE_MODAL_VISIBLE';
export const CHANGE_MODAL_FOCUS = 'CHANGE_MODAL_FOCUS';
export const MODAL_CLOSE = 'MODAL_CLOSE';

