export const CHANGE_LOADING = 'CHANGE_LOADING';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const UPDATE_TODO_ITEMS = 'UPDATE_TODO_ITEMS';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const CHANGE_TODO_ITEM = 'CHANGE_TODO_ITEM';
export const CHANGE_INPUT = 'CHANGE_INPUT';

export const CHANGE_MODAL_VISIBLE = 'CHANGE_MODAL_VISIBLE';
export const CHANGE_MODAL_FOCUS = 'CHANGE_MODAL_FOCUS';
export const CLOSE_MODAL = 'CLOSE_MODAL';
